kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: tystuyfzand/goc:latest
    volumes:
      - name: build
        path: /build
    commands:
      - mkdir -p /build
      - go mod download
      - goc -o /build/gogrok
    environment:
      GOOS: linux,windows,darwin
      GOARCH: 386,amd64,arm,arm64
  - name: package
    image: tystuyfzand/fpm
    commands:
      - chmod +x scripts/build-package.sh
      - ARCH=386 scripts/build-package.sh
      - ARCH=amd64 scripts/build-package.sh
      - ARCH=armv7 scripts/build-package.sh
      - ARCH=arm64 scripts/build-package.sh
    volumes:
      - name: build
        path: /build
    when:
      event: tag
  - name: release
    image: plugins/gitea-release
    volumes:
      - name: build
        path: /build
    settings:
      api_key:
        from_secret: gitea_token
      base_url: https://git.meow.tf
      title: release
      files:
        - /build/gogrok_*
      checksum:
        - md5
        - sha1
        - sha256
    environment:
      PLUGIN_API_KEY:
        from_secret: gitea_token
    when:
      event: tag
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: tystuyfzand/gogrok
      tags:
        - latest
    when:
      event: tag
volumes:
  - name: build
    temp: {}